Criação do botão  Swagger Autorization
acelera-dev-c4/todo-list-notification-backend pull request #17
Opened 2024-06-17 20:43 UTC by Vagner1212

using Api.Middlewares;
using Microsoft.OpenApi.Models;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();

builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Version = "v1" });
    c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Description = "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer { Token}\"",
        Name = "Authorization",
        In = ParameterLocation.Header,
        Type = SecuritySchemeType.ApiKey,
        Scheme = "Bearer"
    }); ;
    c.AddSecurityRequirement(new OpenApiSecurityRequirement()
            {
                {
                    new OpenApiSecurityScheme
                    {
                        Reference = new OpenApiReference
                        {
                            Type = ReferenceType.SecurityScheme,
                            Id = "Bearer"
                        },
                        Scheme = "oauth2",
                        Name = "Bearer",
                        In = ParameterLocation.Header,

                    },
                    new List<string>()
                }
            });
});

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseMiddleware(typeof(ExceptionHandler));

app.UseAuthorization();

app.MapControllers();

app.Run();

2024-06-17 20:53 UTC, raffacabofrio approved these changes

2024-06-17 21:28 UTC, AndersonRFC approved these changes

2024-06-17 21:29 UTC, AndersonRFC commented
pessoal pra testar é necessário colocar: Bearer {token}.
por algum motivo  funciona apenas no https por enquanto, resultando em 401 no http

2024-06-17 22:41 UTC, AndersonRFC requested changes
está removendo muito código, realizar pull na main e atualizar a branch

2024-06-18 00:23 UTC, raffacabofrio approved these changes

2024-06-18 00:23 UTC, merged