feat: new endpoint / method GetSubscriptions + fix
acelera-dev-c4/todo-list-notification-backend pull request #36
Opened 2024-06-24 22:28 UTC by LimaDiogenes

feat: new endpoint GetSubscription / new method GetSubscriptions 
+ 
fix: corrected wrong url being passed to MainTask (ToDoListHttpClient)

2024-06-25 11:28 UTC, AndersonRFC approved these changes

2024-06-25 12:38 UTC, viniciusapsilva requested changes

2024-06-25 12:38 UTC, viniciusapsilva commented on src/Infra/HttpClients/ToDoListHttpClient.cs
isso seria um retrocesso já que alteramos para utilizar o http client factory onde o BaseAddress está sendo atribuido na program.cs, e foi alterado no app settings para TodoListApi em vez de NotificationApi, já que o notification acessa o todo e não ele mesmo

2024-06-25 12:38 UTC, viniciusapsilva commented on src/Infra/HttpClients/ToDoListHttpClient.cs
lembrando que o baseaddress tem que ficar com / no final

2024-06-26 15:33 UTC, raffacabofrio commented on src/Api/Controllers/SubscriptionController.cs
> +    public async Task<IActionResult> GetSubscription()
Pra que serve esse endpoint mesmo?

2024-06-27 01:45 UTC, LimaDiogenes commented on src/Api/Controllers/SubscriptionController.cs
> +    public async Task<IActionResult> GetSubscription()
Busca todas as subscrições. Usado para o UpdateUrl do ToDo, para quando precisar atualizar a url no BD. Nome alterado no último commit para GetSubscriptions.

2024-06-27 17:44 UTC, raffacabofrio commented on src/Api/Controllers/SubscriptionController.cs
> +    public async Task<IActionResult> GetSubscription()
Mas será que a gente precisa mesmo disso? Buscar TODAS as subs me parece algo pesado demais. Se nosso sistema crescer esse endpoint não vai escalar. Nossa aplicação vai ficar lenta ou quebrar. 

vc disse que usa na hora de salvar o UpdateUrl do ToDo. que tal usar um endpoint que já existe? 
GET Subscription/MainTaskId?maintaskId=1

@LimaDiogenes

2024-06-29 14:49 UTC, closed without merging